import { Router, Request, Response } from 'express';
import { supabase } from '../supabaseClient'; // Make sure this path is correct for your setup

const router = Router();

// ==========================================
// 1. GET ALL EMPLOYEES (Kept your custom sorting)
// ==========================================
router.get('/', async (req: Request, res: Response): Promise<any> => {
  try {
    // Fetch all active employees from Supabase
    const { data, error } = await supabase
      .from('Employee')
      .select('*')
      .order('employeeCode', { ascending: true });

    if (error) {
      return res.status(400).json({ error: error.message });
    }

    return res.status(200).json(data);
  } catch (err) {
    return res.status(500).json({ error: "Internal Server Error" });
  }
});

// ==========================================
// 2. GET SINGLE EMPLOYEE (Added for the new Detail View)
// ==========================================
router.get('/:id', async (req: Request, res: Response): Promise<any> => {
  try {
    const { id } = req.params;
    const { data, error } = await supabase.from('Employee').select('*').eq('employeeID', id).single();
    
    if (error) throw error;
    return res.status(200).json(data);
  } catch (err: any) {
    console.error("GET Single Employee Error:", err);
    return res.status(500).json({ error: err.message });
  }
});

// ==========================================
// 3. CREATE A NEW EMPLOYEE (MERGED WITH AUTH & NEW FIELDS)
// ==========================================
router.post('/', async (req: Request, res: Response): Promise<any> => {
  try {
    const data = req.body;
    console.log("--> Incoming Employee Data:", data);

    const fullName = `${data.firstName || ''} ${data.lastName || ''}`.trim();
    const randomNum = Math.floor(1000 + Math.random() * 9000);
    const employeeCode = `EMP-${randomNum}`;
    
    // Enterprise Standard: Assign a default password for new staff
    const defaultPassword = "Password123!"; 

    // 1. LAYER 1: Create the secure login in the Supabase Vault
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email: data.emailAddress, 
      password: defaultPassword,
    });

    if (authError) {
      console.error("Auth Creation Error:", authError);
      return res.status(400).json({ error: authError.message });
    }

    // Grab the new secure UUID generated by the vault
    const newAuthId = authData.user?.id;

    // 2. Format Dates (Supabase hates empty strings for dates)
    const safeDate = (dateStr: string | undefined) => dateStr ? `${dateStr} 00:00:00` : null;

    // 3. LAYER 2: Map frontend variables to Exact Supabase Columns
    const newEmployee = {
      // Kept your custom fields
      employeeCode: employeeCode,
      employeeName: fullName,
      auth_id: newAuthId, // <--- THE BRIDGE IS COMPLETE!
      availability: 'Available',
      
      // New form fields mapped safely
      middleName: data.middleName || null,
      suffix: data.suffix || null,
      role: data.role || 'Helper',
      address: data.address || null,
      contact: data.contactNumber || null, 
      healthStatus: data.healthCondition || 'Fit to work', 
      isActive: data.status === 'Active' || true,
      
      gender: data.gender || null,
      birthdate: safeDate(data.birthdate),
      emailAddress: data.emailAddress || null,
      bloodType: data.bloodType || null,
      nationality: data.nationality || 'Filipino',
      religion: data.religion || null,
      dateEmployed: safeDate(data.dateEmployed),
      
      // Driver Specific
      driverLicenseType: data.driverLicenseType || null,
      licenseNumber: data.licenseNumber || null,
      licenseExpirationDate: safeDate(data.licenseExpirationDate),
      drivingExperience: data.drivingExperience ? parseInt(data.drivingExperience) : null,
      
      // Health & Emergency
      drugTestStatus: data.drugTestStatus || null,
      lastMedicalCheckup: safeDate(data.lastMedicalCheckup),
      emergencyContactPerson: data.emergencyContactPerson || null,
      emergencyContactNumber: data.emergencyContactNumber || null,
      relationship: data.relationship || null,
      
      // Other
      skills: data.skills || null,
      remarks: data.remarks || null
    };

    // 4. Send to Database
    const { data: insertedData, error } = await supabase
      .from('Employee')
      .insert([newEmployee])
      .select();

    if (error) {
      console.error("--> Supabase Rejected Employee:", error);
      return res.status(400).json({ error: error.message, details: error.details });
    }

    // 5. Send the new employee back to the UI
    return res.status(201).json(insertedData[0]);
  } catch (err: any) {
    console.error("--> Express Crashed on Employee POST:", err);
    return res.status(500).json({ error: err.message || "Express Code Crashed" });
  }
});

// ==========================================
// 4. UPDATE EXISTING EMPLOYEE (PUT Route)
// ==========================================
router.put('/:id', async (req: Request, res: Response): Promise<any> => {
  try {
    const { id } = req.params; // Get the ID from the URL (e.g., /api/employees/123)
    const data = req.body;
    
    console.log(`--> Incoming UPDATE Data for Employee ID ${id}:`, data);

    // 1. Format Dates (Supabase hates empty strings for dates)
    const safeDate = (dateStr: string | undefined) => dateStr ? `${dateStr} 00:00:00` : null;

    // 2. Combine First and Last name
    const fullName = `${data.firstName || ''} ${data.lastName || ''}`.trim();

    // 3. Map frontend variables to Exact Supabase Columns
    // Notice we do NOT update the auth_id or employeeCode here!
    const updatedEmployee = {
      employeeName: fullName,
      middleName: data.middleName || null,
      suffix: data.suffix || null,
      role: data.role || 'Helper',
      address: data.address || null,
      contact: data.contactNumber || null, 
      healthStatus: data.healthCondition || 'Fit to work', 
      isActive: data.status === 'Active' || true,
      
      gender: data.gender || null,
      birthdate: safeDate(data.birthdate),
      emailAddress: data.emailAddress || null,
      bloodType: data.bloodType || null,
      nationality: data.nationality || 'Filipino',
      religion: data.religion || null,
      dateEmployed: safeDate(data.dateEmployed),
      
      // Driver Specific
      driverLicenseType: data.driverLicenseType || null,
      licenseNumber: data.licenseNumber || null,
      licenseExpirationDate: safeDate(data.licenseExpirationDate),
      drivingExperience: data.drivingExperience ? parseInt(data.drivingExperience) : null,
      
      // Health & Emergency
      drugTestStatus: data.drugTestStatus || null,
      lastMedicalCheckup: safeDate(data.lastMedicalCheckup),
      emergencyContactPerson: data.emergencyContactPerson || null,
      emergencyContactNumber: data.emergencyContactNumber || null,
      relationship: data.relationship || null,
      
      // Other
      skills: data.skills || null,
      remarks: data.remarks || null
    };

    // 4. Send the Update to Supabase using .eq() to target the specific row
    const { data: result, error } = await supabase
      .from('Employee')
      .update(updatedEmployee)
      .eq('employeeID', id) // Ensure 'employeeID' matches the primary key column name in your DB
      .select();

    if (error) {
      console.error("--> Supabase Update Error:", error);
      return res.status(400).json({ error: error.message, details: error.details });
    }

    return res.status(200).json(result[0]);
  } catch (err: any) {
    console.error("--> Express Crashed on Employee PUT:", err);
    return res.status(500).json({ error: err.message || "Express Code Crashed" });
  }
});

// ==========================================
// 5. DELETE EMPLOYEE
// ==========================================
router.delete('/:id', async (req: Request, res: Response): Promise<any> => {
  try {
    const { id } = req.params;
    console.log(`--> Incoming DELETE Request for Employee ID: ${id}`);

    // Delete from Supabase where the ID matches
    const { data, error } = await supabase
      .from('Employee')
      .delete()
      .eq('employeeID', id) // Ensure this matches your Primary Key column name!
      .select();

    if (error) {
      console.error("--> Supabase Delete Error:", error);
      return res.status(400).json({ error: error.message });
    }

    if (data && data.length === 0) {
      return res.status(404).json({ error: "Employee not found or already deleted." });
    }

    console.log(`--> Successfully deleted Employee ID: ${id}`);
    return res.status(200).json({ 
      message: "Employee successfully deleted", 
      deletedRecord: data[0] 
    });
  } catch (err: any) {
    console.error("--> Express Crashed on Employee DELETE:", err);
    return res.status(500).json({ error: err.message || "Express Code Crashed" });
  }
});

export default router;