import { Router, Request, Response } from 'express';
import { supabase } from '../supabaseClient';

const router = Router();

// ==========================================
// GET ALL EMPLOYEES
// ==========================================
router.get('/', async (req: Request, res: Response): Promise<any> => {
  try {
    // Fetch all active employees from Supabase
    const { data, error } = await supabase
      .from('Employee')
      .select('*')
      .order('employeeCode', { ascending: true });

    if (error) {
      return res.status(400).json({ error: error.message });
    }

    // Send the data back to the frontend
    return res.status(200).json(data);
  } catch (err) {
    return res.status(500).json({ error: "Internal Server Error" });
  }
});

// ==========================================
// CREATE A NEW EMPLOYEE PROFILE (UPGRADED WITH AUTH)
// ==========================================
router.post('/', async (req: Request, res: Response): Promise<any> => {
  try {
    // 1. Catch the email address coming from the frontend modal
    const { firstName, lastName, role, address, contactNumber, healthCondition, emailAddress } = req.body;
    
    const employeeName = `${firstName} ${lastName}`.trim();
    const randomNum = Math.floor(1000 + Math.random() * 9000);
    const employeeCode = `EMP-${randomNum}`;
    
    // Enterprise Standard: Assign a default password for new staff
    const defaultPassword = "Password123!"; 

    // 2. LAYER 1: Create the secure login in the Supabase Vault
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email: emailAddress,
      password: defaultPassword,
    });

    if (authError) {
      console.error("Auth Creation Error:", authError);
      return res.status(400).json({ error: authError.message });
    }

    // Grab the new secure UUID generated by the vault
    const newAuthId = authData.user?.id;

    // 3. LAYER 2: Save the public profile to the Employee table and LINK them
    const { data, error } = await supabase
      .from('Employee')
      .insert([
        {
          employeeCode: employeeCode,
          employeeName: employeeName,
          role: role,
          address: address,
          contact: contactNumber,
          healthStatus: healthCondition || 'Fit to work',
          availability: 'Available',
          auth_id: newAuthId // <--- THE BRIDGE IS COMPLETE!
        }
      ])
      .select();

    if (error) {
      console.error("Supabase Insert Error:", error);
      return res.status(400).json({ error: error.message });
    }

    // 4. Send the new employee back to the UI
    return res.status(201).json(data[0]);
  } catch (err) {
    console.error("Server Error:", err);
    return res.status(500).json({ error: "Internal Server Error" });
  }
});

export default router;